[tool.poetry]
name = "template-c-project"
version = "0.1.0"
description = "Python environment for the template-c-project"
authors = ["Hassan Abedi <hassan.abedi.t@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
