name: Run Test

on:
  workflow_dispatch:  # Allow manual runs
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.12
        with:
          version: 'stable'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          make install-deps

      - name: Run Tests and Generate Coverage Report
        run: make coverage

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/index.html
          fail_ci_if_error: true
          verbose: true
